### ISSUE TITLE
[Request] Window's terminal support

### ISSUE THREAD

**Issue by LonelyMusicDisc** [typicode/bg.nvim#11]
Specifically this one https://github.com/microsoft/terminal

**Comment by typicode** [comment]
Not sure if it's possible. The terminal needs to support some escape sequences to change dynamically the background, if this terminal don't support them, there's nothing that can be done.

Maybe create a feature request to support them or I don't know if they use another escape sequence that `bg.nvim` could use.

You can do some testing with:

```
printf %b '\e]11;rgb:30/00/00\a'
```

On most modern terminal this will change the background color.
