### ISSUE TITLE
Sync in the other way?

### ISSUE THREAD

**Issue by goulf-3m** [typicode/bg.nvim#13]
From the description, I thinks this plugin only syncs in the way: nvim colorscheme -> terminal bg/fg.

How about the other way: terminal bg/fg -> nvim colorscheme (set bg=)?
Personally I prefer this way.

There are such implementations based on dbus in Linux (f-person/auto-dark-mode.nvim), but that should not work when I connect to a remote machine.
Instead, if detection is made using terminal escape sequences, that should work through ssh.

Please implement this if you have time!
Currently, I don't have a suitable NVIM config for this scenario: connect to the same server and run the server nvim, from two client machines, one machine beside the window in light mode, the other in a dark room in dark mode.

**Comment by typicode** [comment]
Sorry, I probably won't have time. Also I often change colorscheme from nvim so it suits my need to not have a "border" around it.
