### ISSUE TITLE
Don't reset color in konsole

### ISSUE THREAD

**Issue by 00sapo** [typicode/bg.nvim#8]
On exit, background color is not reset for konsole

**Comment by typicode** [comment]
Thanks for the report :) If there isn't one already, an issue should probably be created on konsole repo.
I assume it may not support the reset escape code (`\\033]111\\007`).

**Comment by 00sapo** [comment]
There are indeed [some bugs](https://bugs.kde.org/buglist.cgi?quicksearch=ANSI%20product%3Akonsole) related to ANSI code in Konsole. However, I cannot connect this problem to any of those, and neither check if the problem is of konsole. Could you give me a shell script that changes the whole terminal background to a certain color (e.g. black) and then reset it? I'm thinking to something like 

```shell
printf '\e[0mNo background\n\e[41mRed Background\n\e[0mBackground original'
```

However, the above only changes the background of the text. I can't find the proper ANSI code for testing...

**Comment by typicode** [comment]
Currently, I probably won't have much time to spend on this issue. Sorry :/

That being said, this plugin is pretty simple, so you can find all the codes here for testing:
https://github.com/typicode/bg.nvim/blob/main/plugin/bg.lua#L10

For comparisons with Konsole, you can try your shell script with Alacritty or Foot (or a listed terminal), they support the escape sequence.
